create extension if not exists "pgjwt" with schema "extensions";


create extension if not exists "vector" with schema "public" version '0.8.0';

create table "public"."Ad per Ad Account" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "ad_name" text,
    "account_id" text,
    "creative_id" text,
    "ad_text" text,
    "ad_title" text,
    "image" text,
    "video" text,
    "brand" text,
    "post_link" text,
    "Created At" timestamp with time zone,
    "Image_url" text,
    "video_url" text,
    "ad_id" text not null,
    "ad per account" text,
    "Angel" text,
    "Angel Type" text,
    "Explanation" text
);


create table "public"."Cluster Comments" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "comment_id" text not null
);


create table "public"."Comment Claster" (
    "id" bigint generated by default as identity not null,
    "Cluster name" text,
    "Cluster Description" text,
    "Comment" text,
    "Ad" text,
    "meta_cluster" text,
    "created_at" timestamp with time zone not null default now(),
    "ad_id" text,
    "comment_id" text,
    "brand" text
);


create table "public"."Comments" (
    "id" bigint generated by default as identity not null,
    "comment_id" text,
    "message" text,
    "created_time" timestamp without time zone,
    "ad_id" text,
    "created_at" timestamp with time zone not null default now(),
    "theme" text,
    "sentiment" text,
    "brand" text
);


create table "public"."Prompt" (
    "id" bigint generated by default as identity not null,
    "Prompts" text,
    "Name" text,
    "Examples" text,
    "created_at" timestamp with time zone not null default now()
);


create table "public"."comment_assignments" (
    "assignment_id" uuid not null default gen_random_uuid(),
    "comment_id" character varying(255) not null,
    "cluster_id" uuid not null,
    "similarity_score" double precision,
    "assignment_method" character varying(50),
    "confidence_score" double precision,
    "llm_reasoning" text,
    "assigned_at" timestamp with time zone default now()
);


create table "public"."comment_clusters" (
    "cluster_id" uuid not null default gen_random_uuid(),
    "cluster_name" character varying(255),
    "cluster_description" text,
    "meta_cluster" character varying(100),
    "ad_id" character varying(100),
    "centroid_embedding" vector(1536) not null,
    "comment_count" integer default 1,
    "sample_comments" text[] default '{}'::text[],
    "avg_similarity_score" double precision default 0.0,
    "cluster_cohesion" double precision default 0.0,
    "created_at" timestamp with time zone default now(),
    "updated_at" timestamp with time zone default now(),
    "content" text,
    "metadata" jsonb,
    "embedding" vector(1536)
);


create table "public"."comments" (
    "comment_id" character varying(255) not null,
    "ad_id" character varying(100) not null,
    "comment_text" text not null,
    "author_name" character varying(255),
    "likes_count" integer default 0,
    "replies_count" integer default 0,
    "sentiment_score" double precision,
    "theme" character varying(500),
    "sentiment" character varying(50),
    "embedding" vector(1536),
    "embedding_model" character varying(50) default 'text-embedding-3-small'::character varying,
    "comment_created_at" timestamp with time zone,
    "processed_at" timestamp with time zone default now()
);


create table "public"."report_metadata" (
    "id" uuid not null,
    "title" text not null,
    "brand" text not null,
    "created" timestamp with time zone not null,
    "adcount" integer not null
);


create table "public"."reports" (
    "id" uuid not null,
    "data" jsonb not null,
    "created_at" timestamp with time zone default now()
);


CREATE UNIQUE INDEX "Ad per Ad Account_ad_id_key" ON public."Ad per Ad Account" USING btree (ad_id);

CREATE UNIQUE INDEX "Ad per Ad Account_id_key" ON public."Ad per Ad Account" USING btree (id);

CREATE UNIQUE INDEX "Ad per Ad Account_pkey" ON public."Ad per Ad Account" USING btree (id);

CREATE UNIQUE INDEX "Cluster Comments_comment_id_key" ON public."Cluster Comments" USING btree (comment_id);

CREATE UNIQUE INDEX "Cluster Comments_pkey" ON public."Cluster Comments" USING btree (id, comment_id);

CREATE UNIQUE INDEX "Comment Claster_pkey" ON public."Comment Claster" USING btree (id);

CREATE UNIQUE INDEX "Comments_comment_id_key" ON public."Comments" USING btree (comment_id);

CREATE UNIQUE INDEX "Comments_pkey" ON public."Comments" USING btree (id);

CREATE UNIQUE INDEX "Prompt_pkey" ON public."Prompt" USING btree (id);

CREATE UNIQUE INDEX comment_assignments_comment_id_cluster_id_key ON public.comment_assignments USING btree (comment_id, cluster_id);

CREATE UNIQUE INDEX comment_assignments_pkey ON public.comment_assignments USING btree (assignment_id);

CREATE UNIQUE INDEX comment_clusters_pkey ON public.comment_clusters USING btree (cluster_id);

CREATE UNIQUE INDEX comments_pkey ON public.comments USING btree (comment_id);

CREATE INDEX idx_assignments_cluster_id ON public.comment_assignments USING btree (cluster_id);

CREATE INDEX idx_assignments_comment_id ON public.comment_assignments USING btree (comment_id);

CREATE INDEX idx_clusters_ad_id ON public.comment_clusters USING btree (ad_id);

CREATE INDEX idx_clusters_ad_name ON public.comment_clusters USING btree (ad_id, cluster_name);

CREATE INDEX idx_clusters_embedding ON public.comment_clusters USING ivfflat (centroid_embedding vector_cosine_ops) WITH (lists='100');

CREATE INDEX idx_clusters_updated_at ON public.comment_clusters USING btree (updated_at);

CREATE INDEX idx_comments_ad_id ON public.comments USING btree (ad_id);

CREATE INDEX idx_comments_embedding ON public.comments USING ivfflat (embedding vector_cosine_ops) WITH (lists='100');

CREATE INDEX idx_comments_processed_at ON public.comments USING btree (processed_at);

CREATE INDEX idx_report_metadata_brand ON public.report_metadata USING btree (brand);

CREATE INDEX idx_report_metadata_created ON public.report_metadata USING btree (created);

CREATE UNIQUE INDEX report_metadata_pkey ON public.report_metadata USING btree (id);

CREATE UNIQUE INDEX reports_pkey ON public.reports USING btree (id);

alter table "public"."Ad per Ad Account" add constraint "Ad per Ad Account_pkey" PRIMARY KEY using index "Ad per Ad Account_pkey";

alter table "public"."Cluster Comments" add constraint "Cluster Comments_pkey" PRIMARY KEY using index "Cluster Comments_pkey";

alter table "public"."Comment Claster" add constraint "Comment Claster_pkey" PRIMARY KEY using index "Comment Claster_pkey";

alter table "public"."Comments" add constraint "Comments_pkey" PRIMARY KEY using index "Comments_pkey";

alter table "public"."Prompt" add constraint "Prompt_pkey" PRIMARY KEY using index "Prompt_pkey";

alter table "public"."comment_assignments" add constraint "comment_assignments_pkey" PRIMARY KEY using index "comment_assignments_pkey";

alter table "public"."comment_clusters" add constraint "comment_clusters_pkey" PRIMARY KEY using index "comment_clusters_pkey";

alter table "public"."comments" add constraint "comments_pkey" PRIMARY KEY using index "comments_pkey";

alter table "public"."report_metadata" add constraint "report_metadata_pkey" PRIMARY KEY using index "report_metadata_pkey";

alter table "public"."reports" add constraint "reports_pkey" PRIMARY KEY using index "reports_pkey";

alter table "public"."Ad per Ad Account" add constraint "Ad per Ad Account_ad_id_key" UNIQUE using index "Ad per Ad Account_ad_id_key";

alter table "public"."Ad per Ad Account" add constraint "Ad per Ad Account_id_key" UNIQUE using index "Ad per Ad Account_id_key";

alter table "public"."Cluster Comments" add constraint "Cluster Comments_comment id_fkey" FOREIGN KEY (comment_id) REFERENCES "Comments"(comment_id) ON DELETE CASCADE not valid;

alter table "public"."Cluster Comments" validate constraint "Cluster Comments_comment id_fkey";

alter table "public"."Cluster Comments" add constraint "Cluster Comments_comment_id_key" UNIQUE using index "Cluster Comments_comment_id_key";

alter table "public"."Cluster Comments" add constraint "Cluster Comments_id_fkey" FOREIGN KEY (id) REFERENCES "Comment Claster"(id) ON DELETE CASCADE not valid;

alter table "public"."Cluster Comments" validate constraint "Cluster Comments_id_fkey";

alter table "public"."Comments" add constraint "Comments_ad_id_fkey" FOREIGN KEY (ad_id) REFERENCES "Ad per Ad Account"(ad_id) ON DELETE CASCADE not valid;

alter table "public"."Comments" validate constraint "Comments_ad_id_fkey";

alter table "public"."Comments" add constraint "Comments_comment_id_key" UNIQUE using index "Comments_comment_id_key";

alter table "public"."comment_assignments" add constraint "comment_assignments_assignment_method_check" CHECK (((assignment_method)::text = ANY ((ARRAY['hybrid'::character varying, 'embedding_only'::character varying, 'llm_only'::character varying, 'new_cluster'::character varying, 'manual'::character varying])::text[]))) not valid;

alter table "public"."comment_assignments" validate constraint "comment_assignments_assignment_method_check";

alter table "public"."comment_assignments" add constraint "comment_assignments_cluster_id_fkey" FOREIGN KEY (cluster_id) REFERENCES comment_clusters(cluster_id) ON DELETE CASCADE not valid;

alter table "public"."comment_assignments" validate constraint "comment_assignments_cluster_id_fkey";

alter table "public"."comment_assignments" add constraint "comment_assignments_comment_id_cluster_id_key" UNIQUE using index "comment_assignments_comment_id_cluster_id_key";

alter table "public"."comment_assignments" add constraint "comment_assignments_confidence_score_check" CHECK (((confidence_score >= (0)::double precision) AND (confidence_score <= (1)::double precision))) not valid;

alter table "public"."comment_assignments" validate constraint "comment_assignments_confidence_score_check";

alter table "public"."comment_assignments" add constraint "comment_assignments_similarity_score_check" CHECK (((similarity_score >= ('-1'::integer)::double precision) AND (similarity_score <= (1)::double precision))) not valid;

alter table "public"."comment_assignments" validate constraint "comment_assignments_similarity_score_check";

alter table "public"."comment_clusters" add constraint "comment_clusters_comment_count_check" CHECK ((comment_count > 0)) not valid;

alter table "public"."comment_clusters" validate constraint "comment_clusters_comment_count_check";

alter table "public"."comment_clusters" add constraint "comment_clusters_sample_comments_check" CHECK ((array_length(sample_comments, 1) <= 5)) not valid;

alter table "public"."comment_clusters" validate constraint "comment_clusters_sample_comments_check";

alter table "public"."reports" add constraint "reports_id_fkey" FOREIGN KEY (id) REFERENCES report_metadata(id) not valid;

alter table "public"."reports" validate constraint "reports_id_fkey";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.dashboard_metrics(start_date text DEFAULT NULL::text, end_date text DEFAULT NULL::text, brand_filter text DEFAULT NULL::text, sentiment_filter text DEFAULT NULL::text)
 RETURNS json
 LANGUAGE plpgsql
AS $function$
DECLARE
  total_ads integer;
  total_comments integer;
  positive integer;
  negative integer;
  neutral integer;
  positive_pct numeric;
  negative_pct numeric;
  neutral_pct numeric;
BEGIN
  -- Total ads
  SELECT count(*) INTO total_ads
  FROM "Ad per Ad Account" a
  WHERE (start_date IS NULL OR a.created_at >= start_date::date)
    AND (end_date IS NULL OR a.created_at <= end_date::date)
    AND (brand_filter IS NULL OR a.brand = brand_filter);

  -- Total comments
  SELECT count(*) INTO total_comments
  FROM "Comments" c
  WHERE (start_date IS NULL OR c.created_time >= start_date::date)
    AND (end_date IS NULL OR c.created_time <= end_date::date)
    AND (brand_filter IS NULL OR c.brand = brand_filter)
    AND (sentiment_filter IS NULL OR c.sentiment = sentiment_filter);

  -- Sentiment counts
  SELECT count(*) FILTER (WHERE lower(sentiment) = 'positive') INTO positive
  FROM "Comments" c
  WHERE (start_date IS NULL OR c.created_time >= start_date::date)
    AND (end_date IS NULL OR c.created_time <= end_date::date)
    AND (brand_filter IS NULL OR c.brand = brand_filter)
    AND (sentiment_filter IS NULL OR c.sentiment = sentiment_filter);

  SELECT count(*) FILTER (WHERE lower(sentiment) = 'negative') INTO negative
  FROM "Comments" c
  WHERE (start_date IS NULL OR c.created_time >= start_date::date)
    AND (end_date IS NULL OR c.created_time <= end_date::date)
    AND (brand_filter IS NULL OR c.brand = brand_filter)
    AND (sentiment_filter IS NULL OR c.sentiment = sentiment_filter);

  SELECT count(*) FILTER (WHERE lower(sentiment) = 'neutral') INTO neutral
  FROM "Comments" c
  WHERE (start_date IS NULL OR c.created_time >= start_date::date)
    AND (end_date IS NULL OR c.created_time <= end_date::date)
    AND (brand_filter IS NULL OR c.brand = brand_filter)
    AND (sentiment_filter IS NULL OR c.sentiment = sentiment_filter);

  -- Sentiment percentages
  IF total_comments > 0 THEN
    positive_pct := round(positive::numeric * 100 / total_comments, 2);
    negative_pct := round(negative::numeric * 100 / total_comments, 2);
    neutral_pct := round(neutral::numeric * 100 / total_comments, 2);
  ELSE
    positive_pct := 0;
    negative_pct := 0;
    neutral_pct := 0;
  END IF;

  RETURN json_build_object(
    'total_ads', total_ads,
    'total_comments', total_comments,
    'positive', positive,
    'negative', negative,
    'neutral', neutral,
    'positive_pct', positive_pct,
    'negative_pct', negative_pct,
    'neutral_pct', neutral_pct
  );
END;
$function$
;

CREATE OR REPLACE FUNCTION public.dashboard_metrics(start_date timestamp with time zone DEFAULT NULL::timestamp with time zone, end_date timestamp with time zone DEFAULT NULL::timestamp with time zone, brand_filter text DEFAULT NULL::text, sentiment_filter text DEFAULT NULL::text)
 RETURNS jsonb
 LANGUAGE plpgsql
AS $function$
DECLARE
  total_ads int;
  total_comments int;
  positive int;
  negative int;
  neutral int;
BEGIN
  -- Total ads (filtered by brand and business timestamp)
  SELECT COUNT(*) INTO total_ads
    FROM "Ad per Ad Account"
    WHERE (brand_filter IS NULL OR brand = brand_filter)
      AND (start_date IS NULL OR "Created At" >= start_date)
      AND (end_date IS NULL OR "Created At" <= end_date);

  -- Total comments (filtered by business timestamp)
  SELECT COUNT(*) INTO total_comments
    FROM "Comments"
    WHERE (start_date IS NULL OR created_time >= start_date)
      AND (end_date IS NULL OR created_time <= end_date)
      AND (brand_filter IS NULL OR brand = brand_filter)
      AND (sentiment_filter IS NULL OR LOWER(sentiment) = LOWER(sentiment_filter));

  -- Sentiment counts (case-insensitive, filtered by business timestamp)
  SELECT COUNT(*) INTO positive FROM "Comments"
    WHERE LOWER(sentiment) = 'positive'
      AND (start_date IS NULL OR created_time >= start_date)
      AND (end_date IS NULL OR created_time <= end_date)
      AND (brand_filter IS NULL OR brand = brand_filter);

  SELECT COUNT(*) INTO negative FROM "Comments"
    WHERE LOWER(sentiment) = 'negative'
      AND (start_date IS NULL OR created_time >= start_date)
      AND (end_date IS NULL OR created_time <= end_date)
      AND (brand_filter IS NULL OR brand = brand_filter);

  SELECT COUNT(*) INTO neutral FROM "Comments"
    WHERE LOWER(sentiment) = 'neutral'
      AND (start_date IS NULL OR created_time >= start_date)
      AND (end_date IS NULL OR created_time <= end_date)
      AND (brand_filter IS NULL OR brand = brand_filter);

  RETURN jsonb_build_object(
    'total_ads', total_ads,
    'total_comments', total_comments,
    'positive', positive,
    'negative', negative,
    'neutral', neutral,
    'positive_pct', CASE WHEN total_comments > 0 THEN ROUND(positive::numeric / total_comments * 100, 2) ELSE 0 END,
    'negative_pct', CASE WHEN total_comments > 0 THEN ROUND(negative::numeric / total_comments * 100, 2) ELSE 0 END,
    'neutral_pct', CASE WHEN total_comments > 0 THEN ROUND(neutral::numeric / total_comments * 100, 2) ELSE 0 END
  );
END;
$function$
;

CREATE OR REPLACE FUNCTION public.find_similar_clusters(query_embedding vector, target_ad_id character varying, similarity_threshold double precision DEFAULT 0.5, max_results integer DEFAULT 3)
 RETURNS TABLE(cluster_id uuid, cluster_name character varying, cluster_description text, centroid_embedding vector, sample_comments text[], comment_count integer, similarity_score double precision)
 LANGUAGE sql
AS $function$
    select 
        c.cluster_id,
        c.cluster_name,
        c.cluster_description,
        c.centroid_embedding,
        c.sample_comments,
        c.comment_count,
        (c.centroid_embedding <=> query_embedding) * -1 + 1 as similarity_score
    from comment_clusters c
    where c.ad_id = target_ad_id
    and (c.centroid_embedding <=> query_embedding) < (1 - similarity_threshold)
    order by c.centroid_embedding <=> query_embedding
    limit max_results;
$function$
;

CREATE OR REPLACE FUNCTION public.full_dashboard_data(start_date text DEFAULT NULL::text, end_date text DEFAULT NULL::text, brand_filter text DEFAULT NULL::text, sentiment_filter text DEFAULT NULL::text)
 RETURNS json
 LANGUAGE plpgsql
AS $function$
DECLARE
  metrics json;
  top_ads json;
  time_series json;
  all_dates text[];
  actual_start_date date;
BEGIN
  -- If start_date is 1970-01-01 or starts with 1970-01-01, treat as lifetime and use the oldest ad date
  IF start_date IS NOT NULL AND (start_date LIKE '1970-01-01%' OR start_date::date = '1970-01-01') THEN
    SELECT min(created_at)::date INTO actual_start_date FROM "Ad per Ad Account";
  ELSE
    actual_start_date := COALESCE(start_date::date, (SELECT min(created_at)::date FROM "Ad per Ad Account"));
  END IF;

  -- Metrics (reuse existing logic)
  SELECT public.dashboard_metrics(actual_start_date::text, end_date, brand_filter, sentiment_filter) INTO metrics;

  -- Top ads (reuse existing logic)
  SELECT json_agg(t) FROM (
    SELECT ad_id, ad_name, comment_count
    FROM public.top_ads_by_comments(actual_start_date::text, end_date, brand_filter, sentiment_filter, 5)
  ) t INTO top_ads;

  -- Get all dates in range
  SELECT array_agg(date::text) FROM (
    SELECT to_char(d, 'YYYY-MM-DD') AS date
    FROM generate_series(
      actual_start_date,
      COALESCE(end_date::date, (SELECT max(created_time)::date FROM "Comments")),
      interval '1 day'
    ) d
  ) x INTO all_dates;

  -- Build datasets for each sentiment
  SELECT json_build_object(
    'labels', all_dates,
    'datasets', json_agg(
      json_build_object(
        'name', sentiment,
        'data', (
          SELECT array_agg(cnt ORDER BY date_label)
          FROM (
            SELECT d AS date_label,
                   COALESCE(count(c.id), 0) AS cnt
            FROM unnest(all_dates) d
            LEFT JOIN "Comments" c ON to_char(c.created_time, 'YYYY-MM-DD') = d
              AND (brand_filter IS NULL OR c.brand = brand_filter)
              AND (sentiment_filter IS NULL OR c.sentiment = sentiment_filter)
              AND lower(c.sentiment) = lower(sentiment)
            GROUP BY d
            ORDER BY d
          ) sub
        )
      )
    )
  ) INTO time_series
  FROM (SELECT unnest(array['Positive','Negative','Neutral']) AS sentiment) s;

  RETURN json_build_object(
    'metrics', metrics,
    'topAds', top_ads,
    'timeSeriesData', COALESCE(time_series, json_build_object('labels', ARRAY[]::text[], 'datasets', ARRAY[]::json[]))
  );
END;
$function$
;

CREATE OR REPLACE FUNCTION public.period_comparison_metrics(current_start timestamp with time zone, current_end timestamp with time zone, previous_start timestamp with time zone, previous_end timestamp with time zone, brand_filter text DEFAULT NULL::text, sentiment_filter text DEFAULT NULL::text)
 RETURNS jsonb
 LANGUAGE plpgsql
AS $function$
DECLARE
  curr_comments int;
  prev_comments int;
  curr_positive int;
  prev_positive int;
  curr_negative int;
  prev_negative int;
  curr_neutral int;
  prev_neutral int;
BEGIN
  -- Current period
  SELECT COUNT(*) INTO curr_comments FROM "Comments"
    WHERE (brand_filter IS NULL OR brand = brand_filter)
      AND (sentiment_filter IS NULL OR LOWER(sentiment) = LOWER(sentiment_filter))
      AND created_time >= current_start AND created_time <= current_end;
  SELECT COUNT(*) INTO curr_positive FROM "Comments"
    WHERE (brand_filter IS NULL OR brand = brand_filter)
      AND LOWER(sentiment) = 'positive'
      AND created_time >= current_start AND created_time <= current_end;
  SELECT COUNT(*) INTO curr_negative FROM "Comments"
    WHERE (brand_filter IS NULL OR brand = brand_filter)
      AND LOWER(sentiment) = 'negative'
      AND created_time >= current_start AND created_time <= current_end;
  SELECT COUNT(*) INTO curr_neutral FROM "Comments"
    WHERE (brand_filter IS NULL OR brand = brand_filter)
      AND LOWER(sentiment) = 'neutral'
      AND created_time >= current_start AND created_time <= current_end;

  -- Previous period
  SELECT COUNT(*) INTO prev_comments FROM "Comments"
    WHERE (brand_filter IS NULL OR brand = brand_filter)
      AND (sentiment_filter IS NULL OR LOWER(sentiment) = LOWER(sentiment_filter))
      AND created_time >= previous_start AND created_time <= previous_end;
  SELECT COUNT(*) INTO prev_positive FROM "Comments"
    WHERE (brand_filter IS NULL OR brand = brand_filter)
      AND LOWER(sentiment) = 'positive'
      AND created_time >= previous_start AND created_time <= previous_end;
  SELECT COUNT(*) INTO prev_negative FROM "Comments"
    WHERE (brand_filter IS NULL OR brand = brand_filter)
      AND LOWER(sentiment) = 'negative'
      AND created_time >= previous_start AND created_time <= previous_end;
  SELECT COUNT(*) INTO prev_neutral FROM "Comments"
    WHERE (brand_filter IS NULL OR brand = brand_filter)
      AND LOWER(sentiment) = 'neutral'
      AND created_time >= previous_start AND created_time <= previous_end;

  RETURN jsonb_build_object(
    'current_total_comments', curr_comments,
    'previous_total_comments', prev_comments,
    'comments_change_pct', CASE WHEN prev_comments > 0 THEN ROUND((curr_comments::numeric - prev_comments) / prev_comments * 100, 2) ELSE NULL END,
    'current_positive', curr_positive,
    'previous_positive', prev_positive,
    'positive_change_pct', CASE WHEN prev_positive > 0 THEN ROUND((curr_positive::numeric - prev_positive) / prev_positive * 100, 2) ELSE NULL END,
    'current_negative', curr_negative,
    'previous_negative', prev_negative,
    'negative_change_pct', CASE WHEN prev_negative > 0 THEN ROUND((curr_negative::numeric - prev_negative) / prev_negative * 100, 2) ELSE NULL END,
    'current_neutral', curr_neutral,
    'previous_neutral', prev_neutral,
    'neutral_change_pct', CASE WHEN prev_neutral > 0 THEN ROUND((curr_neutral::numeric - prev_neutral) / prev_neutral * 100, 2) ELSE NULL END
  );
END;
$function$
;

CREATE OR REPLACE FUNCTION public.populate_cluster_from_metadata()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
DECLARE
    base_name text;
    counter integer := 1;
    final_name text;
BEGIN
    -- If metadata exists, populate the fields
    IF NEW.metadata IS NOT NULL THEN
        base_name := NEW.metadata->>'cluster_name';
        final_name := base_name;
        
        -- Check if cluster name already exists for this ad_id
        WHILE EXISTS (
            SELECT 1 FROM comment_clusters 
            WHERE cluster_name = final_name 
            AND ad_id = NEW.metadata->>'ad_id'
            AND cluster_id != NEW.cluster_id
        ) LOOP
            counter := counter + 1;
            final_name := base_name || '_' || counter;
        END LOOP;
        
        NEW.cluster_name := final_name;
        NEW.cluster_description := COALESCE(NEW.cluster_description, NEW.content);
        NEW.ad_id := COALESCE(NEW.ad_id, NEW.metadata->>'ad_id');
        NEW.meta_cluster := COALESCE(NEW.meta_cluster, NEW.metadata->>'meta_cluster');
        NEW.comment_count := COALESCE(NEW.comment_count, (NEW.metadata->>'comment_count')::integer, 1);
        
        -- Set the centroid_embedding to the same as embedding if not set
        NEW.centroid_embedding := COALESCE(NEW.centroid_embedding, NEW.embedding);
    END IF;
    
    RETURN NEW;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.set_ad_account_comment_id()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
BEGIN
  -- Check if ad_id is not null in the new row
  IF NEW.ad_id IS NOT NULL THEN
    -- Fetch the most recent comment_id from "Comments" table using ad_id
    SELECT comment_id INTO NEW.comment
    FROM public."Comments"
    WHERE ad_id = NEW.ad_id
    ORDER BY created_time DESC -- Assuming created_time indicates recency
    LIMIT 1;

    -- If no comment is found, set the comment column to NULL
    IF NOT FOUND THEN
      NEW.comment := NULL;
    END IF;
  ELSE
    -- If ad_id is null, set the comment column to NULL
    NEW.comment := NULL;
  END IF;

  -- Return the modified new row
  RETURN NEW;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.set_comment_brand()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
BEGIN
  -- Check if ad_id is not null in the new row
  IF NEW.ad_id IS NOT NULL THEN
    -- Fetch the brand from "Ad per Ad Account" table using ad_id
    SELECT brand INTO NEW.brand
    FROM public."Ad per Ad Account"
    WHERE ad_id = NEW.ad_id;
  END IF;

  -- Return the modified new row
  RETURN NEW;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.top_ads_by_comments(start_date text DEFAULT NULL::text, end_date text DEFAULT NULL::text, brand_filter text DEFAULT NULL::text, sentiment_filter text DEFAULT NULL::text, limit_count integer DEFAULT 5)
 RETURNS TABLE(ad_id text, ad_name text, comment_count integer)
 LANGUAGE plpgsql
AS $function$
BEGIN
  RETURN QUERY
    SELECT
      a.ad_id::text,
      a.ad_name::text,
      COUNT(c.id)::integer AS comment_count
    FROM "Ad per Ad Account" a
    LEFT JOIN "Comments" c ON a.ad_id = c.ad_id
      AND (start_date IS NULL OR c.created_time >= start_date::date)
      AND (end_date IS NULL OR c.created_time <= end_date::date)
      AND (sentiment_filter IS NULL OR c.sentiment = sentiment_filter)
    WHERE (brand_filter IS NULL OR a.brand = brand_filter)
    GROUP BY a.ad_id, a.ad_name
    ORDER BY comment_count DESC
    LIMIT limit_count;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.top_ads_by_comments(start_date timestamp with time zone DEFAULT NULL::timestamp with time zone, end_date timestamp with time zone DEFAULT NULL::timestamp with time zone, brand_filter text DEFAULT NULL::text, sentiment_filter text DEFAULT NULL::text, limit_count integer DEFAULT 5)
 RETURNS TABLE(ad_id text, ad_name text, comment_count integer)
 LANGUAGE plpgsql
AS $function$
BEGIN
  RETURN QUERY
    SELECT a.ad_id, a.ad_name, COUNT(c.id)::int AS comment_count
    FROM "Ad per Ad Account" a
    LEFT JOIN "Comments" c ON a.ad_id = c.ad_id
      AND (start_date IS NULL OR c.created_time >= start_date)
      AND (end_date IS NULL OR c.created_time <= end_date)
      AND (sentiment_filter IS NULL OR LOWER(c.sentiment) = LOWER(sentiment_filter))
    WHERE (brand_filter IS NULL OR a.brand = brand_filter)
    GROUP BY a.ad_id, a.ad_name
    ORDER BY comment_count DESC
    LIMIT limit_count;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.update_ad_account_comment_on_new_comment()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
BEGIN
  -- Check if ad_id is not null in the new comment row
  IF NEW.ad_id IS NOT NULL THEN
    -- Update the "Ad per Ad Account" table with the new comment_id
    UPDATE public."Ad per Ad Account"
    SET comment = NEW.comment_id
    WHERE ad_id = NEW.ad_id;
  END IF;

  -- This is an AFTER trigger, so we just return the new row
  RETURN NEW;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.update_cluster_centroid(target_cluster_id uuid, new_embedding vector, new_comment_text text)
 RETURNS void
 LANGUAGE plpgsql
AS $function$
declare
    current_centroid vector(1536);
    current_count integer;
    current_samples text[];
    updated_centroid vector(1536);
begin
    -- Get current cluster data
    select centroid_embedding, comment_count, sample_comments
    into current_centroid, current_count, current_samples
    from comment_clusters 
    where cluster_id = target_cluster_id;
    
    if not found then
        raise exception 'Cluster not found: %', target_cluster_id;
    end if;
    
    -- Calculate new centroid (weighted average)
    select (
        select array_agg(
            (curr_val * current_count + new_val) / (current_count + 1)
        )
        from unnest(current_centroid::float[]) with ordinality as curr(curr_val, i),
             unnest(new_embedding::float[]) with ordinality as new(new_val, j)
        where curr.i = new.j
    )::vector(1536) into updated_centroid;
    
    -- Update sample comments (keep max 5)
    if array_length(current_samples, 1) < 5 then
        current_samples := current_samples || array[new_comment_text];
    end if;
    
    -- Update cluster
    update comment_clusters 
    set 
        centroid_embedding = updated_centroid,
        comment_count = comment_count + 1,
        updated_at = now(),
        sample_comments = current_samples
    where cluster_id = target_cluster_id;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.update_comment_brand()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
begin
  update "Comments"
  set brand = (
    select brand
    from "Ad per Ad Account"
    where "Ad per Ad Account".ad_id = NEW.ad_id
    limit 1
  )
  where id = NEW.id;

  return NEW;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.update_comment_brand_from_ad_account()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
DECLARE
    comment_ad_id_text TEXT;
    ad_account_brand_text TEXT;
BEGIN
    -- Extract the first element from the comment's ad_id array string
    BEGIN
        comment_ad_id_text := (NEW.ad_id::jsonb)->>0;
    EXCEPTION WHEN others THEN
        RAISE WARNING 'Failed to parse comment ad_id "%" as JSON array. Skipping brand update for this comment.', NEW.ad_id;
        RETURN NEW; -- Keep the brand as null
    END;

    -- Find the brand from "Ad per Ad Account" using the extracted ad_id
    SELECT (a.brand::jsonb)->>0 -- Extract the first element from the brand array string
    INTO ad_account_brand_text
    FROM public."Ad per Ad Account" AS a
    WHERE a.ad_id = comment_ad_id_text; -- Match extracted text ad_id with text ad_id in Ad per Ad Account

    -- If a matching brand was found, set it in the new comment row
    IF FOUND THEN
        NEW.brand := ad_account_brand_text;
    ELSE
        RAISE WARNING 'No matching ad_id "%" found in "Ad per Ad Account". Cannot set brand for comment.', comment_ad_id_text;
        -- Keep the brand as null if no match is found
    END IF;

    -- Return the modified new row
    RETURN NEW;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.update_comment_cluster_brand_from_ad_account()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
DECLARE
    comment_cluster_ad_id_val TEXT;
    ad_account_brand_val TEXT;
    ad_account_brand_raw TEXT;
BEGIN
    -- Handle ad_id from NEW.ad_id
    BEGIN
        -- Try to parse as jsonb and get the first element if it's an array
        IF NEW.ad_id IS NOT NULL AND jsonb_typeof(NEW.ad_id::jsonb) = 'array' THEN
            comment_cluster_ad_id_val := (NEW.ad_id::jsonb)->>0;
        ELSE
            -- Otherwise, treat as plain text
            comment_cluster_ad_id_val := NEW.ad_id;
        END IF;
    EXCEPTION WHEN others THEN
        -- If casting to jsonb fails, treat as plain text
        comment_cluster_ad_id_val := NEW.ad_id;
    END;

    -- Find the brand from "Ad per Ad Account" using the extracted ad_id
    SELECT brand INTO ad_account_brand_raw
    FROM public."Ad per Ad Account" AS a
    WHERE a.ad_id = comment_cluster_ad_id_val;

    -- If a matching brand was found, process it and set it in the new comment_clusters row
    IF FOUND THEN
        BEGIN
            -- Try to parse as jsonb and get the first element if it's an array
            IF ad_account_brand_raw IS NOT NULL AND jsonb_typeof(ad_account_brand_raw::jsonb) = 'array' THEN
                ad_account_brand_val := (ad_account_brand_raw::jsonb)->>0;
            ELSE
                -- Otherwise, treat as plain text
                ad_account_brand_val := ad_account_brand_raw;
            END IF;
        EXCEPTION WHEN others THEN
            -- If casting to jsonb fails, treat as plain text
            ad_account_brand_val := ad_account_brand_raw;
        END;
        NEW.brand := ad_account_brand_val;
    ELSE
        RAISE WARNING 'No matching ad_id "%" found in "Ad per Ad Account". Cannot set brand for comment cluster.', comment_cluster_ad_id_val;
    END IF;

    RETURN NEW;
END;
$function$
;

grant delete on table "public"."Ad per Ad Account" to "anon";

grant insert on table "public"."Ad per Ad Account" to "anon";

grant references on table "public"."Ad per Ad Account" to "anon";

grant select on table "public"."Ad per Ad Account" to "anon";

grant trigger on table "public"."Ad per Ad Account" to "anon";

grant truncate on table "public"."Ad per Ad Account" to "anon";

grant update on table "public"."Ad per Ad Account" to "anon";

grant delete on table "public"."Ad per Ad Account" to "authenticated";

grant insert on table "public"."Ad per Ad Account" to "authenticated";

grant references on table "public"."Ad per Ad Account" to "authenticated";

grant select on table "public"."Ad per Ad Account" to "authenticated";

grant trigger on table "public"."Ad per Ad Account" to "authenticated";

grant truncate on table "public"."Ad per Ad Account" to "authenticated";

grant update on table "public"."Ad per Ad Account" to "authenticated";

grant delete on table "public"."Ad per Ad Account" to "service_role";

grant insert on table "public"."Ad per Ad Account" to "service_role";

grant references on table "public"."Ad per Ad Account" to "service_role";

grant select on table "public"."Ad per Ad Account" to "service_role";

grant trigger on table "public"."Ad per Ad Account" to "service_role";

grant truncate on table "public"."Ad per Ad Account" to "service_role";

grant update on table "public"."Ad per Ad Account" to "service_role";

grant delete on table "public"."Cluster Comments" to "anon";

grant insert on table "public"."Cluster Comments" to "anon";

grant references on table "public"."Cluster Comments" to "anon";

grant select on table "public"."Cluster Comments" to "anon";

grant trigger on table "public"."Cluster Comments" to "anon";

grant truncate on table "public"."Cluster Comments" to "anon";

grant update on table "public"."Cluster Comments" to "anon";

grant delete on table "public"."Cluster Comments" to "authenticated";

grant insert on table "public"."Cluster Comments" to "authenticated";

grant references on table "public"."Cluster Comments" to "authenticated";

grant select on table "public"."Cluster Comments" to "authenticated";

grant trigger on table "public"."Cluster Comments" to "authenticated";

grant truncate on table "public"."Cluster Comments" to "authenticated";

grant update on table "public"."Cluster Comments" to "authenticated";

grant delete on table "public"."Cluster Comments" to "service_role";

grant insert on table "public"."Cluster Comments" to "service_role";

grant references on table "public"."Cluster Comments" to "service_role";

grant select on table "public"."Cluster Comments" to "service_role";

grant trigger on table "public"."Cluster Comments" to "service_role";

grant truncate on table "public"."Cluster Comments" to "service_role";

grant update on table "public"."Cluster Comments" to "service_role";

grant delete on table "public"."Comment Claster" to "anon";

grant insert on table "public"."Comment Claster" to "anon";

grant references on table "public"."Comment Claster" to "anon";

grant select on table "public"."Comment Claster" to "anon";

grant trigger on table "public"."Comment Claster" to "anon";

grant truncate on table "public"."Comment Claster" to "anon";

grant update on table "public"."Comment Claster" to "anon";

grant delete on table "public"."Comment Claster" to "authenticated";

grant insert on table "public"."Comment Claster" to "authenticated";

grant references on table "public"."Comment Claster" to "authenticated";

grant select on table "public"."Comment Claster" to "authenticated";

grant trigger on table "public"."Comment Claster" to "authenticated";

grant truncate on table "public"."Comment Claster" to "authenticated";

grant update on table "public"."Comment Claster" to "authenticated";

grant delete on table "public"."Comment Claster" to "service_role";

grant insert on table "public"."Comment Claster" to "service_role";

grant references on table "public"."Comment Claster" to "service_role";

grant select on table "public"."Comment Claster" to "service_role";

grant trigger on table "public"."Comment Claster" to "service_role";

grant truncate on table "public"."Comment Claster" to "service_role";

grant update on table "public"."Comment Claster" to "service_role";

grant delete on table "public"."Comments" to "anon";

grant insert on table "public"."Comments" to "anon";

grant references on table "public"."Comments" to "anon";

grant select on table "public"."Comments" to "anon";

grant trigger on table "public"."Comments" to "anon";

grant truncate on table "public"."Comments" to "anon";

grant update on table "public"."Comments" to "anon";

grant delete on table "public"."Comments" to "authenticated";

grant insert on table "public"."Comments" to "authenticated";

grant references on table "public"."Comments" to "authenticated";

grant select on table "public"."Comments" to "authenticated";

grant trigger on table "public"."Comments" to "authenticated";

grant truncate on table "public"."Comments" to "authenticated";

grant update on table "public"."Comments" to "authenticated";

grant delete on table "public"."Comments" to "service_role";

grant insert on table "public"."Comments" to "service_role";

grant references on table "public"."Comments" to "service_role";

grant select on table "public"."Comments" to "service_role";

grant trigger on table "public"."Comments" to "service_role";

grant truncate on table "public"."Comments" to "service_role";

grant update on table "public"."Comments" to "service_role";

grant delete on table "public"."Prompt" to "anon";

grant insert on table "public"."Prompt" to "anon";

grant references on table "public"."Prompt" to "anon";

grant select on table "public"."Prompt" to "anon";

grant trigger on table "public"."Prompt" to "anon";

grant truncate on table "public"."Prompt" to "anon";

grant update on table "public"."Prompt" to "anon";

grant delete on table "public"."Prompt" to "authenticated";

grant insert on table "public"."Prompt" to "authenticated";

grant references on table "public"."Prompt" to "authenticated";

grant select on table "public"."Prompt" to "authenticated";

grant trigger on table "public"."Prompt" to "authenticated";

grant truncate on table "public"."Prompt" to "authenticated";

grant update on table "public"."Prompt" to "authenticated";

grant delete on table "public"."Prompt" to "service_role";

grant insert on table "public"."Prompt" to "service_role";

grant references on table "public"."Prompt" to "service_role";

grant select on table "public"."Prompt" to "service_role";

grant trigger on table "public"."Prompt" to "service_role";

grant truncate on table "public"."Prompt" to "service_role";

grant update on table "public"."Prompt" to "service_role";

grant delete on table "public"."comment_assignments" to "anon";

grant insert on table "public"."comment_assignments" to "anon";

grant references on table "public"."comment_assignments" to "anon";

grant select on table "public"."comment_assignments" to "anon";

grant trigger on table "public"."comment_assignments" to "anon";

grant truncate on table "public"."comment_assignments" to "anon";

grant update on table "public"."comment_assignments" to "anon";

grant delete on table "public"."comment_assignments" to "authenticated";

grant insert on table "public"."comment_assignments" to "authenticated";

grant references on table "public"."comment_assignments" to "authenticated";

grant select on table "public"."comment_assignments" to "authenticated";

grant trigger on table "public"."comment_assignments" to "authenticated";

grant truncate on table "public"."comment_assignments" to "authenticated";

grant update on table "public"."comment_assignments" to "authenticated";

grant delete on table "public"."comment_assignments" to "service_role";

grant insert on table "public"."comment_assignments" to "service_role";

grant references on table "public"."comment_assignments" to "service_role";

grant select on table "public"."comment_assignments" to "service_role";

grant trigger on table "public"."comment_assignments" to "service_role";

grant truncate on table "public"."comment_assignments" to "service_role";

grant update on table "public"."comment_assignments" to "service_role";

grant delete on table "public"."comment_clusters" to "anon";

grant insert on table "public"."comment_clusters" to "anon";

grant references on table "public"."comment_clusters" to "anon";

grant select on table "public"."comment_clusters" to "anon";

grant trigger on table "public"."comment_clusters" to "anon";

grant truncate on table "public"."comment_clusters" to "anon";

grant update on table "public"."comment_clusters" to "anon";

grant delete on table "public"."comment_clusters" to "authenticated";

grant insert on table "public"."comment_clusters" to "authenticated";

grant references on table "public"."comment_clusters" to "authenticated";

grant select on table "public"."comment_clusters" to "authenticated";

grant trigger on table "public"."comment_clusters" to "authenticated";

grant truncate on table "public"."comment_clusters" to "authenticated";

grant update on table "public"."comment_clusters" to "authenticated";

grant delete on table "public"."comment_clusters" to "service_role";

grant insert on table "public"."comment_clusters" to "service_role";

grant references on table "public"."comment_clusters" to "service_role";

grant select on table "public"."comment_clusters" to "service_role";

grant trigger on table "public"."comment_clusters" to "service_role";

grant truncate on table "public"."comment_clusters" to "service_role";

grant update on table "public"."comment_clusters" to "service_role";

grant delete on table "public"."comments" to "anon";

grant insert on table "public"."comments" to "anon";

grant references on table "public"."comments" to "anon";

grant select on table "public"."comments" to "anon";

grant trigger on table "public"."comments" to "anon";

grant truncate on table "public"."comments" to "anon";

grant update on table "public"."comments" to "anon";

grant delete on table "public"."comments" to "authenticated";

grant insert on table "public"."comments" to "authenticated";

grant references on table "public"."comments" to "authenticated";

grant select on table "public"."comments" to "authenticated";

grant trigger on table "public"."comments" to "authenticated";

grant truncate on table "public"."comments" to "authenticated";

grant update on table "public"."comments" to "authenticated";

grant delete on table "public"."comments" to "service_role";

grant insert on table "public"."comments" to "service_role";

grant references on table "public"."comments" to "service_role";

grant select on table "public"."comments" to "service_role";

grant trigger on table "public"."comments" to "service_role";

grant truncate on table "public"."comments" to "service_role";

grant update on table "public"."comments" to "service_role";

grant delete on table "public"."report_metadata" to "anon";

grant insert on table "public"."report_metadata" to "anon";

grant references on table "public"."report_metadata" to "anon";

grant select on table "public"."report_metadata" to "anon";

grant trigger on table "public"."report_metadata" to "anon";

grant truncate on table "public"."report_metadata" to "anon";

grant update on table "public"."report_metadata" to "anon";

grant delete on table "public"."report_metadata" to "authenticated";

grant insert on table "public"."report_metadata" to "authenticated";

grant references on table "public"."report_metadata" to "authenticated";

grant select on table "public"."report_metadata" to "authenticated";

grant trigger on table "public"."report_metadata" to "authenticated";

grant truncate on table "public"."report_metadata" to "authenticated";

grant update on table "public"."report_metadata" to "authenticated";

grant delete on table "public"."report_metadata" to "service_role";

grant insert on table "public"."report_metadata" to "service_role";

grant references on table "public"."report_metadata" to "service_role";

grant select on table "public"."report_metadata" to "service_role";

grant trigger on table "public"."report_metadata" to "service_role";

grant truncate on table "public"."report_metadata" to "service_role";

grant update on table "public"."report_metadata" to "service_role";

grant delete on table "public"."reports" to "anon";

grant insert on table "public"."reports" to "anon";

grant references on table "public"."reports" to "anon";

grant select on table "public"."reports" to "anon";

grant trigger on table "public"."reports" to "anon";

grant truncate on table "public"."reports" to "anon";

grant update on table "public"."reports" to "anon";

grant delete on table "public"."reports" to "authenticated";

grant insert on table "public"."reports" to "authenticated";

grant references on table "public"."reports" to "authenticated";

grant select on table "public"."reports" to "authenticated";

grant trigger on table "public"."reports" to "authenticated";

grant truncate on table "public"."reports" to "authenticated";

grant update on table "public"."reports" to "authenticated";

grant delete on table "public"."reports" to "service_role";

grant insert on table "public"."reports" to "service_role";

grant references on table "public"."reports" to "service_role";

grant select on table "public"."reports" to "service_role";

grant trigger on table "public"."reports" to "service_role";

grant truncate on table "public"."reports" to "service_role";

grant update on table "public"."reports" to "service_role";

CREATE TRIGGER set_brand_on_comment_cluster BEFORE INSERT OR UPDATE ON public."Comment Claster" FOR EACH ROW EXECUTE FUNCTION update_comment_cluster_brand_from_ad_account();

CREATE TRIGGER set_brand_on_comment BEFORE INSERT OR UPDATE ON public."Comments" FOR EACH ROW EXECUTE FUNCTION set_comment_brand();

CREATE TRIGGER populate_cluster_trigger BEFORE INSERT ON public.comment_clusters FOR EACH ROW EXECUTE FUNCTION populate_cluster_from_metadata();


