-- This migration creates the 'brands' table and adds a foreign key
-- reference to it from the 'ad_per_ad_account' table.

-- =================================================================
--  1. Create the 'brands' table
-- =================================================================
CREATE TABLE public.brands (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default now(),
    brand_name text not null unique,
    logo text null, -- Storing a URL to the logo in Supabase Storage
    is_ad_analyzing boolean not null default false,
    is_comment_analyzing boolean not null default false
);

-- =================================================================
--  2. Enable Row Level Security (RLS) on the new table
--     This is crucial for making the table accessible via the API.
-- =================================================================
ALTER TABLE public.brands ENABLE ROW LEVEL SECURITY;

-- =================================================================
--  3. Create RLS policies for the 'brands' table
--     This example allows authenticated users to perform all actions.
--     You can tighten these rules as needed.
-- =================================================================
CREATE POLICY "Enable all actions for authenticated users"
ON public.brands
FOR ALL
USING (auth.role() = 'authenticated')
WITH CHECK (auth.role() = 'authenticated');


-- =================================================================
--  4. Add the 'brand_id' column to the 'ad_per_ad_account' table
-- =================================================================
ALTER TABLE public.ad_per_ad_account
ADD COLUMN brand_id bigint;


-- =================================================================
--  5. Add the foreign key constraint to link the tables
-- =================================================================
ALTER TABLE public.ad_per_ad_account
ADD CONSTRAINT ad_per_ad_account_brand_id_fkey
FOREIGN KEY (brand_id) REFERENCES public.brands(id) ON DELETE SET NULL;