-- Create the "clusters" table.
CREATE TABLE public.clusters (
    -- Use BIGINT and GENERATED BY DEFAULT AS IDENTITY for a modern, robust primary key.
    cluster_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- A unique name for the cluster.
    cluster_name VARCHAR(255) NOT NULL UNIQUE,

    -- A description for the cluster.
    cluster_description TEXT NOT NULL,

    -- A flag to indicate if the cluster is active.
    is_active BOOLEAN NOT NULL DEFAULT TRUE,

    -- Timestamp with timezone is recommended for web applications.
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
